// <auto-generated />
namespace wateen12148MCVWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addlocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlocation));
        
        string IMigrationMetadata.Id
        {
            get { return "202603310620094_add-location"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
